# Generated by Django 3.2.9 on 2023-01-06 21:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_job_jobapplication_jobposting_resume_tweet'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassionProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('members', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='resume',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
