# Generated by Django 3.2.9 on 2023-01-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20230108_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_mentor_requested',
            field=models.BooleanField(default=False),
        ),
    ]
