# Generated by Django 3.2.9 on 2023-01-09 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_is_mentor_requested'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='job',
        ),
        migrations.DeleteModel(
            name='PassionProject',
        ),
        migrations.DeleteModel(
            name='Resume',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='user',
        ),
        migrations.DeleteModel(
            name='JobApplication',
        ),
        migrations.DeleteModel(
            name='JobPosting',
        ),
        migrations.DeleteModel(
            name='Tweet',
        ),
    ]
