# Generated by Django 3.2.9 on 2023-01-06 02:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.profile')),
                ('areas_of_expertise', models.TextField()),
                ('coaching_experience', models.TextField()),
            ],
            bases=('users.profile',),
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Order ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('quantity', models.DecimalField(decimal_places=0, max_digits=2, verbose_name='Quantity')),
                ('pricePer', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price per Unit')),
                ('totalPaid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Paid')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_placed_by', to='users.profile')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_received_by', to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('option1', 'Option 1'), ('option2', 'Option 2'), ('option3', 'Option 3'), ('option4', 'Option 4')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('units_available', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=50)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
