# Generated by Django 3.2.9 on 2023-01-08 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_is_mentor_requested'),
        ('mentors', '0003_auto_20230108_1841'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
