# Generated by Django 3.2.9 on 2023-01-09 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0004_rename_orders_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
